### ISSUE TITLE
bower won't unzip files created with 0.11.0

### ISSUE THREAD

**Issue by jpmec** [gruntjs/grunt-contrib-compress#127]
I have been using grunt-contrib-compress 0.10.0 to create .zip files that are used by bower.
When I switched to grunt-contrib-compres 0.11.0, bower began complaining about the zip files.

```
Bower version: 1.3.9
Node version: 0.10.28
OS: Windows_NT 6.1.7601 x64
PS D:\Projects\myotherproject> bower install
bower not-cached    D:\Projects\mybrokenproject\python\dist\mybrokenproject-0.5.0.zip#*
bower resolve       D:\Projects\mybrokenproject\python\dist\mybrokenproject-0.5.0.zip#*
bower copy          D:\Projects\mybrokenproject\python\dist\mybrokenproject-0.5.0.zip
bower extract       mybrokenproject#* mybrokenproject-0.5.0.zip
bower error         Unsupported file type "undefined"
```

Here is the snippet from the Gruntfile used to for the compress task:

```
compress:
  distPython:
    options:
      archive: "<%= metaPython.distPath %><%= pkg.name %>-<%= pkg.version %>.zip"

    files: [
      expand: true
      cwd: "<%= metaPython.addPath %>"
      src: ["bower.json"]
      dest: "./"
    ,
      expand: true
      cwd: "<%= metaPython.distPath %><%= pkg.name %>-<%= pkg.version %>"
      src: ["**"]
      dest: "./<%= pkg.name %>-<%= pkg.version %>/"
    ]
```

In general, steps to reproduce are:

1) Use grunt-contrib-compress to create a .zip file with the following structure:

```
+ mybrokenproject-0.5.0.zip
|
+- bower.json
|
+- /mybrokenproject-0.5.0
   |
   +- ...other files...
```

2) Try to use the .zip file with a bower.json file similar to:

```
{
  "name": "myotherproject",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "mybrokenproject": "D:\\Projects\\mybrokenproject\\python\\dist\\mybrokenproject-0.5.0.zip",
   }
}
```

I can provide whatever other details are needed.
For now I am switching back to the 0.10.0 version.
