### ISSUE TITLE
Is it possible to replace the file in the same location?

### ISSUE THREAD

**Issue by SimplGy** [gruntjs/grunt-contrib-compress#61]
This is more convenient, as I've already built my css and js package to a dist folder using other steps in the build chain.

Is it supposed to be possible to do a configuration like this in a way that replaces the existing file? (instead of adding the .gz extension)

This method adds .gz as a sibling:
```
    compress:
      options: pretty: true
      mainPackages:
        files: [
          "<%= grunt.option('target') %>all-min.css": "<%= grunt.option('target') %>/all-min.css"
          "<%= grunt.option('target') %>all-min.js": "<%= grunt.option('target') %>/all-min.js"
        ]
```

This method creates a corrupted file 20 bytes in length:
```
    compress:
      options: pretty: true
      mainPackages:
        expand: true
        cwd: "<%= grunt.option('target') %>"
        src: '**/{<%= cfg.minName %>.css,core/main.js}'
        dest: "<%= grunt.option('target') %>"
        ext: ''
```
